### ISSUE TITLE
Não ativou na versão 3.0.6.3

### ISSUE THREAD

**Issue by whande1992** [opencartbrasil/ocmod-editor#12]
A instalação é realizada sem problemas aparente, verifiquei as permissões de pastas e até tentei instalando de forma manual, porém não esta ativando. O log de erros das extensões ele retorna essas informações:

OC Versão 3.0.3.6
----------------------------------------------------------------
MOD: OCMOD Editor for OpenCart 3.0.x

FILE: admin/controller/startup/permission.php
CODE: $extension = array(
LINE: 18

**Comment by v5mvidal** [comment]
O problema não ocorre por causa do OCMOD Editor, mas sim por um bug que é específico da versão 3.0.3.6

Para resolver o bug, altere o conteúdo do arquivo abaixo:
system/**modification.xml**

Pelo conteúdo do arquivo abaixo:
https://github.com/opencart/opencart/blob/3.0.x.x_Maintenance/upload/system/modification.xml

Por fim atualize o cache do OCMOD através da administração de sua loja que o problema será resolvido.
