### ISSUE TITLE
[bug] SyntaxError: in

### ISSUE THREAD

**Issue by yvonn** [opencartbrasil/ocmod-editor#14]
OpenCart 3.0.3.7 and 3.0.3.8 (and maybe earlier) there is an error in editor file. When you hit edit button on an xml file and use "erase twig/sass cache" button, an error appear and the cache template folder is not erased.

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data .....

**I replaced this**
`$directories = glob(DIR_CACHE . '*', GLOB_ONLYDIR);` 
on line 262 of admin/controller/extension/modification/editor.php 
**into this**
`$directories = glob(DIR_CACHE . '/template/*', GLOB_ONLYDIR);`

Result: error disappear and folder cache/template/ is erased.

Can you confirm this is correct?

**Comment by v5mvidal** [comment]
I will analyze the problem!

**Comment by v5mvidal** [comment]
revised!
