### ISSUE TITLE
[bug] PHP Notice: Undefined index: filename in

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/ocmod-editor#15]
Após atualizar para versão 3.4.0, aparece vários erros no log.

13-04-2022 9:18:00 - PHP Notice:  Undefined index: filename in /www/wwwroot/dominio/system/storage/modification/admin/controller/marketplace/modification.php on line 710

**Comment by rlasmar** [comment]
Também aparece outro erro, quando acessa a parte de arquivos modificados.

PHP Notice:  Undefined offset: 71 in /www/wwwroot/dominio/admin/controller/extension/modification/files.php on line 113

**Comment by v5mvidal** [comment]
Envie um e-mail para nossa equipe pelo:
suporte@opencartbrasil.com.br

Informe um usuário e senha de acesso para a administração da loja com o problema, para que possamos analisar o que ocasionou o problema, pois em nossos ambientes de testes o erro não ocorre.

**Comment by rlasmar** [comment]
Enviei os dados por email com mais detalhes dos erros

**Comment by v5mvidal** [comment]
Resolvido!
