### ISSUE TITLE
[bug] Arquivos modificados mostrando arquivo zip que não tem relação com a modificação

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/ocmod-editor#16]
Na parte da listagem de arquivos modificados, alguns não mostram qual arquivo zip está modificando, e outros que mostram estão mostrando arquivo zip que não tem relação com a modificação.

![1](https://user-images.githubusercontent.com/37814975/163195945-8b32b220-1f8c-4433-871e-723bf2d97155.JPG)

**Comment by v5mvidal** [comment]
Envie um e-mail para nossa equipe pelo:
[suporte@opencartbrasil.com.br](mailto:suporte@opencartbrasil.com.br)

Informe um usuário e senha de acesso para a administração da loja com o problema, para que possamos analisar o que ocasionou o problema, pois em nossos ambientes de testes o erro não ocorre.

**Comment by v5mvidal** [comment]
Corrigido!
