### ISSUE TITLE
Problema com permissão de acesso a página

### ISSUE THREAD

**Issue by vynnus** [opencartbrasil/ocmod-editor#3]
Na minha loja (2.0.1.1) sempre ao clicar em editar qualquer modificação retorna a mensagem:

Permissão negada!
Você não tem permissão para acessar esta página, consulte o administrador do loja para mais informações.

Todas as permissões setadas para o grupo Administrador.

**Comment by v5mvidal** [comment]
Conseguiu resolver?

**Comment by vynnus** [comment]
Sim, era cache. Só funcionou após limpar o cache e reiniciar o PC.
