### ISSUE TITLE
Errors after trying to save ocmod xml changes

### ISSUE THREAD

**Issue by alexander-mart** [opencartbrasil/ocmod-editor#7]
Errors after trying to save ocmod xml changes

Version of OpenCart: 2.3.0.2

This is my log: https://pastebin.com/raw/E9yCyGY4

This is the same issue: #6

**Comment by v5mvidal** [comment]
After install, click Refresh button in menu Extensions→Modifications.

**Comment by 7oda187** [comment]
Dear v5manoel.

This issue showing every time when click on clear button.
Is there any fix for this ?

**Comment by v5mvidal** [comment]
@7oda187 When you clean the modifications cache the problem occurs because the OCMOD Editor is removed. Not a problem, but the result of clearing the cache.

**Comment by 7oda187** [comment]
I see, so three is no problem with that.
