### ISSUE TITLE
Add some return buttons - version 3

### ISSUE THREAD

**Issue by yvonn** [opencartbrasil/ocmod-editor#8]
Maybe some solutions!

admin/controller/extension/modification/diff.php
Delete line 60:
`$data['return'] = $this->url->link('extension/modification', 'user_token=' . $this->session->data['user_token'], true);`

Add:
`$data['return'] = $this->url->link('extension/modification/files', 'user_token=' . $this->session->data['user_token'], true);`

admin/language/en-gb/extension/modification/diff.php
Add:
// Button
`$_['button_return']      = 'Return modified files';`

admin/view/template/extension/modification/diff.twig
Add below line 4:
`      <div class="pull-right">
        <a href="{{ return }}" data-toggle="tooltip" title="{{ button_return }}" class="btn btn-default"><i class="fa fa-reply"></i></a>
      </div>`

admin/controller/extension/modification/files.php
Add below line 55:
`        $data['button_return'] = $this->language->get('button_return');
        $data['return'] = $this->url->link('marketplace/modification', 'user_token=' . $this->session->data['user_token'], true);`

admin/language/en-gb/extension/modification/files.php
Add:
// Button
`$_['button_return']      = 'Return modifications';`

admin/view/template/extension/modification/files.twig
Add below line 4:
`      <div class="pull-right">
        <a href="{{ return }}" data-toggle="tooltip" title="{{ button_return }}" class="btn btn-default"><i class="fa fa-reply"></i></a>
      </div>`

And Delete target="_blank" at line 34:
target="_blank"

admin/controller/extension/modification/error_log.php
Add below line 58:
`        $data['button_return'] = $this->language->get('button_return');
        $data['return'] = $this->url->link('marketplace/modification', 'user_token=' . $this->session->data['user_token'], true);`

admin/language/en-gb/extension/modification/error_log.php
Add:
// Button
`$_['button_return']      = 'Return modifications';`

admin/view/template/extension/modification/error_log.twig
Add below line 6:
`        <a href="{{ return }}" data-toggle="tooltip" title="{{ button_return }}" class="btn btn-default"><i class="fa fa-reply"></i></a>`

**Comment by v5mvidal** [comment]
Thanks for the suggestion, I will implement.

**Comment by yvonn** [comment]
One button to add.
admin/view/template/extension/modification/error_log.twig
Add below line 6
`<a href="{{ clear }}" data-toggle="tooltip" title="{{ button_clear }}" class="btn btn-warning"><i class="fa fa-eraser"></i></a>`

**Comment by v5mvidal** [comment]
This button is not necessary because the log is cleaned each time you access the error log page.. =)

**Comment by yvonn** [comment]
So the download button is also not necessary?

**Comment by v5mvidal** [comment]
The download button is required because the merchant can send the error log to a developer.

What is important is to understand that this error log is automatically deleted and generated every time the page loads, because its function is to display errors caused by OCMOD modifications in real time. =)

**Comment by yvonn** [comment]
I am a little confused :-( 
The clear button is not necesarry because the log is cleaned each time you access the error log page.
The download button is required because the error log (the download file) can be send to a developer.
Accessing the error_log will automatically delete the error log. This means the error log is empty and cannot be downloaded. Or do I miss something else.

**Comment by v5mvidal** [comment]
There is no confusion, the download button downloads the current error log, and if the error is corrected, when accessing the page with OCMOD error log, the log is automatically updated, only the current errors are displayed or no error. =)

**Comment by yvonn** [comment]
ah ok tx

**Comment by v5mvidal** [comment]
I thank you for the contribution. =D
